baseURL = "http://powercall.pt/"
languageCode = "en-us"
title = "Powercall"
theme = "bigspring"

# allow html in text fields
[markup.goldmark.renderer]
unsafe = true

[params.variables]
primary_color = "#f4581b"
text_color = "#777"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#f4581b"
black = "#000"
white = "#fff"
light = "#fef3e6"
