# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Contact"
url = "contact"
weight = 2

[[main]]
name = "Resources"
url = "resources"
weight = 3

# footer menu left
[[footer_left]]
name = "About Us"
url = "about"

[[footer_left]]
name = "Careers"
url = "careers"

# footer menu middle
[[footer_middle]]
name = "Resources"
url = "resources"

[[footer_right]]
name = "Contacts"
url = "contact"
